services:
  db:
    image: mysql
    container_name: chat-app-mysql
    environment:
      MYSQL_DATABASE: chat-app
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"


  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat-app-spring
    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/chat-app
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

    depends_on:
      - db

volumes:
  db_data:
